# Modified SRResNet w/o BN from:
# Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network

# general settings
name: 003_MSRResNet_DF2KVIDEO_120k_B32_GPU4
model_type: SRModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2KVIDEO
    type: PairedImageDataset
    dataroot_gt: ""
    dataroot_lq: ""
    meta_info_file: /opt/data/private/142/BasicSR/experiments_watermark/DF2KVIDEO/check_data/train.txt
    meta_with_dir: true
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    use_hflip: true
    use_rot: false

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: DF2KVIDEO
    type: PairedImageDataset
    dataroot_gt: ""
    dataroot_lq: ""
    meta_info_file: /opt/data/private/142/BasicSR/experiments_watermark/DF2KVIDEO/check_data/test.txt
    meta_with_dir: true
    io_backend:
      type: disk

# network structures
network_g:
  type: MSRResNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16
  upscale: 1

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: false
  experiments_root: /opt/data/private/142/BasicSR/experiments

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [30000, 30000, 30000, 30000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 120000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
