# general settings
name: 002_SwinIR_DF2K_60k_B8_GPU4
model_type: SwinIRModel
scale: 1
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /opt/data/share/xtkong/DF2K/GT_demask
    dataroot_lq: /opt/data/share/xtkong/DF2K/mask_demask
    meta_info_file: /opt/data/private/142/BasicSR/experiments_watermark/DF2K/check_data/train.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /opt/data/share/xtkong/DF2K/GT_demask
    dataroot_lq: /opt/data/share/xtkong/DF2K/mask_demask
    meta_info_file: /opt/data/private/142/BasicSR/experiments_watermark/DF2K/check_data/test.txt
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 1
  in_chans: 3
  img_size: [100, 400]
  window_size: 10
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~
  experiments_root: /opt/data/private/142/BasicSR/experiments

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [30000, 40000, 50000, 55000]
    gamma: 0.5

  total_iter: 60000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
